image
assist-software/internship-2022-july-be2-UNDEFINED pull request #36
Opened 2022-07-21 14:36 UTC by gherghelalessandro

2022-07-21 14:51 UTC, HincuAndreiAssist requested changes

2022-07-21 14:51 UTC, HincuAndreiAssist commented on source/Assist.Jully.2022.BE2/Assist.July._2022.BE2.Application/Services/UserService.cs
> +            string SasKey = "?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2022-08-16T17:30:43Z&st=2022-07-20T09:30:43Z&sip=0.0.0.0-255.255.255.255&spr=https&sig=RReu5GnC4EjJqvE63A00A3iK6gLCOJp9
You should get the SasKey from appsettings

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new BadRequestObjectResult("{'message':'user not found'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                await UserService.Register(email,password);
you should use a DTO

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new OkObjectResult("{'message':'ok'};");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new BadRequestObjectResult("{'message':'user already exist'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new OkObjectResult("{ 'message':'ok' };");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new BadRequestObjectResult("{'message':'mail not found'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new OkObjectResult("{ 'message':'ok' }");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new NotFoundObjectResult("{'message':'user not found'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new NotFoundObjectResult("{'message':'User not found'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new NotFoundObjectResult("{'message':'user not found'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new NotFoundObjectResult("{'message':'Empty'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new OkObjectResult("{ 'message':'ok' }");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.Jully.2022.BE2/Controllers/UserController.cs
> +                return new NotFoundObjectResult("{'message':'user not found'}");
you should return a DTO, not hardcode the message

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.July._2022.BE2.Application/Interfaces/IUserService.cs
> +        Task Register(string Email,string Password);
space between properties, also the properties should be camelCase, not PascalCase

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.July._2022.BE2.Application/Interfaces/IUserService.cs
>          Task ResetPassword(string Email);
same comment as before

2022-07-22 08:14 UTC, SebastianFulgaAssist commented on source/Assist.Jully.2022.BE2/Assist.July._2022.BE2.Application/Interfaces/IUserService.cs
>          Task<User> GetUserEmail(string Email);
camelCase

2022-07-22 09:47 UTC, SebastianFulgaAssist approved these changes

2022-07-22 09:52 UTC, merged